### PR TITLE
Migrate to new webpack 4 plugin system

### PR DESCRIPTION
**Pull request by JakeChampion**
I've kept the previous version of the plugin to ensure this still works with Webpack versions 2 and 3.

### CODE REVIEW

**Review by chrisfinch — APPROVED** [review]
👍 would be great to get this in!

**Comment by chrisfinch** [comment]
@codewizz would be great to get a response on this!

**Comment by JakeChampion** [comment]
It may be simpler to review the changes by ignoring any whitespace-only changes in the diff --> https://github.com/codewizz/bower-resolve-webpack-plugin/pull/4/files?w=1

**Comment by linaspasv** [comment]
Hello, thank you for your PR! 👍  Sorry for this taking so long to be merged.

**Comment by JakeChampion** [comment]
Thank you for the review/merge/release @linaspasv ❤️

**Pull request merged**
